name = "sample-cf-wasm"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:wasm"

[[rules]]
type = "Data"
globs = ["**/*.wasm"]
fallthrough = true 