[package]
name = "cf-wasm-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# No dependencies needed for raw WASM exports - better for static imports
[dependencies]

# Tell `rustc` to optimize for small code size.
[profile.release]
opt-level = "s" 